---
- name: Configure cron to monitor machine
  hosts: cron-servers
  become: yes
  gather_facts: no
  tasks:
    - name: Ensure cron is installed
      package:
        name: cron
        state: present
    - name: Upload bash script
      copy:
        src: "{{ playbook_dir }}/../../../scripts/budoman-backend/monitor_resources.sh"
        dest: /budoman-backend/bin/monitor_resources.sh
    - name: schedule task in cron
      cron:
        name: Monitor machine
        minute: "*"
        job: bash /budoman-backend/bin/monitor_resources.sh http://localhost:3333/graphql
