all:
  hosts:
    budoman-backend-1:
      env: production
      ansible_ssh_host: ec2-3-71-52-7.eu-central-1.compute.amazonaws.com
      ansible_ssh_port: 22
      ansible_ssh_user: ubuntu
      host: https://ec2-3-71-52-7.eu-central-1.compute.amazonaws.com
      ansible_ssh_private_key_file: ~/.ssh/aws_budoman
      env_path: /home/ubuntu
