all:
  hosts:
    budoman-front-1:
      ansible_ssh_host: ec2-52-59-215-21.eu-central-1.compute.amazonaws.com
      ansible_ssh_port: 22
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/aws_budoman
      env: production
      env_path: /home/ubuntu
