all:
  hosts:
    budoman-backend:
      env: development
      ansible_ssh_host: localhost
      ansible_ssh_port: 2222
      ansible_ssh_user: root
      host: http://localhost:3333
      env_path: /budoman-backend
