---
- name: Upload evironment variables
  hosts: all
  gather_facts: no
  tasks:
    - name: Copy .env file on remote hosts
      copy:
        src: "{{ playbook_dir }}/../../secrets/budoman-monitoring-system/{{ env }}/env.yml"
        dest: /budoman-monitoring-system/.env
