---
- name: Upload evironment variables
  hosts: all
  gather_facts: no
  tasks:
    - name: Upload .env file on remote hosts
      copy:
        src: "{{ playbook_dir }}/../../secrets/budoman-backend/{{ env }}/env.yml"
        dest: "{{ env_path }}/.env"
